# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kdIsGg7tlBU5Zxz0MK9UWUO2uWqNzHxK
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df.info()

df.head(11)

df.tail()

df.describe()

df = df.drop_duplicates()

df['Date'] = pd.to_datetime(df['Date'])

df.isnull().sum()