# -*- coding: utf-8 -*-
"""TEST2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FuJ_3O5nmlLwvIpCVKeQYQhQtGZTSJVO
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel("/content/sample_data/AAPL.xlsx")

df.head()

df.columns

df.dtypes

df["Date"] = pd.to_datetime(df["Date"])

df = df.sort_values("Date")

df.info()

df.tail()

plt.figure(figsize=(12, 6))

plt.plot(df["Date"], df["Open"], label="Open")
plt.plot(df["Date"], df["High"], label="High")
plt.plot(df["Date"], df["Low"], label="Low")
plt.plot(df["Date"], df["Close"], label="Close")

plt.title("AAPL OHLC Prices Over Time")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()


plt.show()

plt.figure(figsize=(12, 5))

plt.plot(df["Date"], df["Volume"])

plt.title("AAPL Trading Volume Over Time")
plt.xlabel("Date")
plt.ylabel("Trading Volume")


plt.show()

df["Daily_Return"] = df["Close"].pct_change()

print("\nDaily Returns:")
print(df["Daily_Return"].head())

plt.figure(figsize=(10, 6))

sns.histplot(
    df["Daily_Return"].dropna(),
    bins=30,
    kde=True
)

plt.title("AAPL Daily Returns Distribution using histogram")
plt.xlabel("Daily Return")
plt.ylabel("Frequency")


plt.show()