# -*- coding: utf-8 -*-
"""superstore.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10GJDb0XJmpmWzmwq_9HDNJIRrgj_nvfQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from scipy import stats
from google.colab import files

# Upload the dataset if not already present
# This will open a file selection dialog. Please select your 'samplesuperstore - samplesuperstore.csv' file.
files.upload()

# Load the dataset
# If you encounter a FileNotFoundError, please ensure 'samplesuperstore - samplesuperstore.csv' is uploaded to your Colab session's files.
# You can upload files using the 'Files' icon on the left sidebar in Colab or by running `from google.colab import files; files.upload()`.
path = "/content/samplesuperstore - samplesuperstore.csv"
df = pd.read_csv(path)

# Display first 5 rows
print(df.head())

# Display dataset information
print(df.info())

# Check for missing values
print(df.isnull().sum())

# Average Sales
print("Average Sales:", np.mean(df["Sales"]))

# Sales by Category
sales = df.groupby("Category")["Sales"].sum()
print(sales)

# Bar Chart
plt.figure(figsize=(6,4))
plt.bar(sales.index, sales.values)
plt.title("Sales by Category")
plt.xlabel("Category")
plt.ylabel("Sales")
plt.show()

# Scatter Plot
plt.figure(figsize=(6,4))
sns.scatterplot(data=df, x="Sales", y="Profit")
plt.title("Sales vs Profit")
plt.show()

# Train-Test Split
X_train, X_test = train_test_split(df, test_size=0.2, random_state=42)

print("Training Rows:", len(X_train))
print("Testing Rows:", len(X_test))

# Mean Sales using scipy
print("Mean Sales:", stats.tmean(df["Sales"]))