# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oOMrk-UZZ1ZsqzP5zJjr3Melu06EN4CM
"""

import pandas as pd
import numpy as np

df = pd.read_csv("StudentsPerformance.csv")

df.head()

df.info()

df.tail()

df.columns

df.dtypes

df.isnull().sum()

df.describe()

categorical_features = {
    "gender",
    "race/ethnicity",
    "parental level of education",
    "lunch",
    "test preparation course"
}

for col in categorical_features:
    df[col] = df[col].str.strip().str.title()
df[list(categorical_features)].head()