# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZEvQUxTg6OVBi24rkKE_rULsizYC-t1H
"""

import pandas as pd


df = pd.read_csv('healthcare_dataset.csv')


display(df.head())

display(df.info())

display(df.describe())

df.dtypes

df.columns

df.isnull().sum()

df.isnull()

df['Medical Condition'].isnull().sum()

df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Date of Admission']

df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])
df['Discharge Date']

df['Admission Type'].value_counts()

df['Admission Type'] = (
    df['Admission Type']
    .str.lower()
)

df.describe()

df["Admission Type"]

df["Hospital Stay (Days)"]=(df["Discharge Date"]-df["Date of Admission"]).dt.days
df["Hospital Stay (Days)"].head()

df["Billing Amount"].describe()