# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/153mP_SQ-D1iIsNlw2sxm1E1JlTTvkl5g
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("healthcare_dataset.csv")

df.info()

df.head()

df.tail()

df.columns

df.dtypes

df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Admission Month'] = df['Date of Admission'].dt.month_name()
monthly_admissions = df.groupby('Admission Month').size().sort_values()

monthly_admissions

plt.figure(figsize=(12,6))
monthly_admissions.plot()
plt.title('Monthly Admissions')
plt.xlabel('Month')
plt.ylabel('Number of Admissions')
plt.xticks(rotation=45)
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

correlation_matrix = df[["Age", "Billing Amount"]].corr()
correlation_matrix

import seaborn as sns
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', vmin=-1, vmax=1)
plt.show()