# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KH5YdJpmwa8X62KlekE1d3q7NN-1xKnT
"""

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import pandas as pd

df = pd.read_csv("/content/StudentsPerformance_preprocessed.csv")
df.columns = ["gender","race","parent_edu","lunch","test_prep","math","reading","writing"]
scores = ["math","reading","writing"]

for col in ["parent_edu", "lunch"]:
    df.groupby(col)[scores].mean().plot(kind="bar", figsize=(10,5), title=f"Average scores by {col}")
    plt.ylabel("Mean score"); plt.xticks(rotation=30); plt.tight_layout(); plt.show()

long = df.melt(id_vars="test_prep", value_vars=scores, var_name="subject", value_name="score")
sns.boxplot(data=long, x="subject", y="score", hue="test_prep")
plt.title("Scores by test preparation"); plt.show()

sns.pairplot(df[scores], kind="reg"); plt.show()

sns.heatmap(df[scores].corr(), annot=True, cmap="coolwarm", vmin=0.5, vmax=1)
plt.title("Correlation heatmap"); plt.show()